### ISSUE TITLE
delta_login_review

### ISSUE THREAD

**Issue by mrqaidi** [Miljan9602/Instagram-API#3]
Hi

can you also add support for delta_login_review ?

**Comment by Miljan9602** [comment]
Hello, this is already supported, here is the request. It is in Challenge class of request package.

public function resolveChallenge($choice) {

        return $this->ig->request("challenge/")
            ->setNeedsAuth(false)
            ->addPost('_csrftoken', $this->ig->client->getToken())
            ->addPost('_uuid', $this->ig->uuid)
            ->addPost('choice', $choice)
            ->addPost('device_id', $this->ig->device_id)
            ->addPost('_uid', $this->ig->account_id)
            ->addPost('guid', $this->ig->uuid)
            ->getResponse(new Response\ResolveChallenge());
    }

**Comment by mrqaidi** [comment]
but how to detect it in first place for example when i  use login function is tells me  ChallengeRequiredException  but with  none set of getApiPath  thats means its delta type
